### ISSUE TITLE
Sending "metric" as 0 results in :metric being nil

### ISSUE THREAD

**Issue by cventers** [miquelruiz/Riemann-Client#9]
This line in Riemann/Client.pm should probably read ``if exists $_->{metric}``. Setting a 0 value to the metric key results in a nil metric being sent to Riemann instead of the 0.

``
        $_->{metric_d} = delete $_->{metric} if $_->{metric};
``

**Comment by miquelruiz** [comment]
Yes, that looks right :)
Fix incoming...
